# Generated by Django 5.0.3 on 2024-04-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
