# Generated by Django 5.0.3 on 2024-04-06 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='datetime',
        ),
        migrations.AddField(
            model_name='listing',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
