# Generated by Django 5.0.3 on 2024-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Broomstick', 'Broomstick'), ('Wand', 'Wand'), ('Cloak', 'Cloak'), ('Clothes', 'Clothes'), ('Hat', 'Hat')], default='Broomstick', max_length=20),
        ),
    ]
