# Generated by Django 5.0.3 on 2024-04-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Broomstick', 'Broomstick'), ('Cloak', 'Cloak'), ('Clothes', 'Clothes'), ('Hat', 'Hat'), ('None', 'No Category'), ('Wand', 'Wand')], default='None', max_length=20),
        ),
    ]
